# HTMLバリデーションとリンクチェック
name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: HTML Validation
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
          
      - name: Check file size
        run: |
          echo "ファイルサイズチェック:"
          ls -lh index.html
          
      - name: Check for console errors
        run: |
          echo "console.log/error チェック:"
          ! grep -E "console\.(log|error)" index.html || echo "⚠️ デバッグコードが含まれています"